# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/7va01f1pa6bkxy2a869dx148ajxx16dd-cmake-3.31.6/bin/cmake

# The command to remove a file.
RM = /nix/store/7va01f1pa6bkxy2a869dx148ajxx16dd-cmake-3.31.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artyom/RoltonBasic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artyom/RoltonBasic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/7va01f1pa6bkxy2a869dx148ajxx16dd-cmake-3.31.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/7va01f1pa6bkxy2a869dx148ajxx16dd-cmake-3.31.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artyom/RoltonBasic/CMakeFiles /home/artyom/RoltonBasic//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artyom/RoltonBasic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named roltonbasic

# Build rule for target.
roltonbasic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 roltonbasic
.PHONY : roltonbasic

# fast build rule for target.
roltonbasic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/build
.PHONY : roltonbasic/fast

compiler.o: compiler.cpp.o
.PHONY : compiler.o

# target to build an object file
compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/compiler.cpp.o
.PHONY : compiler.cpp.o

compiler.i: compiler.cpp.i
.PHONY : compiler.i

# target to preprocess a source file
compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/compiler.cpp.i
.PHONY : compiler.cpp.i

compiler.s: compiler.cpp.s
.PHONY : compiler.s

# target to generate assembly for a file
compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/compiler.cpp.s
.PHONY : compiler.cpp.s

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/parser.cpp.s
.PHONY : parser.cpp.s

rolton-basic.o: rolton-basic.cpp.o
.PHONY : rolton-basic.o

# target to build an object file
rolton-basic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/rolton-basic.cpp.o
.PHONY : rolton-basic.cpp.o

rolton-basic.i: rolton-basic.cpp.i
.PHONY : rolton-basic.i

# target to preprocess a source file
rolton-basic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/rolton-basic.cpp.i
.PHONY : rolton-basic.cpp.i

rolton-basic.s: rolton-basic.cpp.s
.PHONY : rolton-basic.s

# target to generate assembly for a file
rolton-basic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/roltonbasic.dir/build.make CMakeFiles/roltonbasic.dir/rolton-basic.cpp.s
.PHONY : rolton-basic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... roltonbasic"
	@echo "... compiler.o"
	@echo "... compiler.i"
	@echo "... compiler.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... rolton-basic.o"
	@echo "... rolton-basic.i"
	@echo "... rolton-basic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

